### ISSUE TITLE
[QUESTION] Usefulness of indexes with GUID key

### ISSUE THREAD

**Issue by lxman** [litedb-org/LiteDB#2562]
I know there a number of discussions regarding using GUID's as keys in Sql Server. How does the indexing in LiteDB interact with GUIDs. Are they necessarily a bad idea?

**Comment by Joy-less** [comment]
I don't know about SQL server, but GUIDs work fine in LiteDB. They are stored as JSON (e.g. `{"$guid": "f29595f7-68f1-4dd0-b309-7583c85a0c84"}`). Since they are globally unique, they should work well in all scenarios. It is my understanding that LiteDB indexing works with GUIDs (although according to the [docs](https://www.litedb.org/docs/data-structure), "Unlike the Guid data type, ObjectIds are sequential, so it’s a better solution for indexing").

There a couple of downsides to GUIDs:
- Unlike ObjectIds and auto-incremented integers, they are not sequential (not in order).
- They take up the most memory (although likely negligible).

Please re-open the issue if you still have questions.
